il doit pas en manquer gros
CIDCO-dev/Poseidon pull request #247
Opened 2021-11-12 17:11 UTC by patcmorneau

le logger crash une fois que le threshold est depassé

le output :

```
process[hydroball_data_websocket-8]: started with pid [90383]
process[hydroball_files_websocket-9]: started with pid [90385]
Opening NMEA device /dev/sonar
0.035
0.0694583
...
0.987098
1.01989
[logger_text-7] process has died [pid 90374, exit code -11, cmd /home/ubuntu/Poseidon/src/workspace/devel/lib/logger_text/logger_text_node /home/ubuntu/Poseidon/www/webroot/record/ __name:=logger_text __log:=/home/ubuntu/.ros/log/85ab7d1e-43d9-11ec-832f-2f9bbd356eb1/logger_text-7.log].
log file: /home/ubuntu/.ros/log/85ab7d1e-43d9-11ec-832f-2f9bbd356eb1/logger_text-7*.log
[logger_text-7] restarting process
process[logger_text-7]: started with pid [90408]
0.0375

```

2021-11-12 18:27 UTC, patcmorneau commented
ca sa fonctionne donc pas de probleme de permission:

```

	if (average_speed >= threshold){
		std::ofstream myfile;
  		myfile.open ("/home/ubuntu/Poseidon/www/webroot/record/logger_speed_test.txt", std::ios::out | std::ios::app);
	  	myfile << speed.header.stamp.sec << " " << speed.header.stamp.nsec << " " << current_speed <<"\n";
	 	myfile.close();
	}
```

2021-11-12 18:54 UTC, glabmoris requested changes

2021-11-12 18:54 UTC, glabmoris commented on src/workspace/src/logger_text/include/logger_text/logger_text.h
> +		FILE * speedOutputFile = NULL;
On ne log pas la vitesse. On utilise la vitesse pour toggler le logging de la profondeur, IMU et GNSS.

2021-11-12 18:54 UTC, glabmoris commented on src/workspace/src/logger_text/src/logger_text.cpp
> +	average_speed = std::accumulate(kmh_Speed_list.begin(),kmh_Speed_list.end(),average_speed) / 120;
On ne devrait pas calculer la vitesse moyenne ni logger si la liste n'est pas pleine. Ça devrait se retrouver dans le "else" à la ligne 143

2021-11-22 19:27 UTC, merged

2021-11-22 19:28 UTC, glabmoris commented
Closes #247